### ISSUE TITLE
Missing custom widgets?

### ISSUE THREAD

**Issue by rduivenvoorde** [opengisch/qgis_geomapfish_locator#1]
Hi Denis, 
Wanted to install on pretty recent master (less then 4 days old):

![selection_520](https://user-images.githubusercontent.com/731673/40773709-03f2cb30-64c4-11e8-949f-b120274a5305.png)

Do I have to 'install' custom widgets somewhere? I'm doing a 'ninja install' here in my own homedir without root permissions...

 Or is something not packaged?

**Comment by 3nids** [comment]
I think you need to have the file qgis_customwidgets.py installed in the uic plugins dir.
Something like /usr/local/lib/python3.6/site-packages/PyQt5/uic/widget-plugins/qgis_customwidgets.py

But can you try replacing
`from PyQt5.uic import loadUiType` by `from qgis.PyQt.uic import loadUiType` in geomapfish_locator_filter.py and tell me if that helps?

**Comment by rduivenvoorde** [comment]
@3nids I downloaded latest version which already had `from qgis.PyQt.uic import loadUiType` but did not fix.

I copied the qgis_customwidgets.py from my build dir to (Debian)
`/usr/lib/python3/dist-packages/PyQt5/uic/widget-plugins` and then it works....

I think there is no other way to put it in another (as in without being root) place is it? The normal installer scripts do copy it to there?

**Comment by rduivenvoorde** [comment]
Note: is there some testing key? Just interested to test it...

Note2: about custom qgis widgets: should we not have a searchable tree widget? Would be cool to use it in all the WMS, WFS, Oracle layer etc etc...

**Comment by 3nids** [comment]
@rduivenvoorde can you try if https://github.com/qgis/QGIS/pull/7130 fixes the issue for you?

**Comment by 3nids** [comment]
fixed upstream
