### ISSUE TITLE
Issue installing the plugin on QGIS 3.22.X

### ISSUE THREAD

**Issue by kalbermattenm** [opengisch/qgis_geomapfish_locator#11]
Hello,

We have some issues trying to install the plugin on version 3.22.X of QGIS. The error here under appears while installing the plugin.

![image](https://user-images.githubusercontent.com/1681332/192758333-ef91767b-1897-4f22-8eeb-a2290f5b7e13.png)

After that, it looks like the plugin is installed, but each time you try to activate it, the error reappears.

Is this a known issue?

**Comment by 3nids** [comment]
should be fixed in 1.3.2
