### ISSUE TITLE
 Sous windows depuis le passage à Geomapfish Locator 1.3.2: Impossible de charger l'extension 'geomapfish_locator' provoque une erreur lors de l'appel à sa méthode classFactory()

### ISSUE THREAD

**Issue by spch-GL** [opengisch/qgis_geomapfish_locator#12]
2022-09-28T15:59:42     CRITICAL    Traceback (most recent call last):
              File "....python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "....plugins\geomapfish_locator\__init__.py", line 36, in classFactory
              return GeomapfishLocatorPlugin(iface)
              File "....plugins\geomapfish_locator\core\geomapfish_locator_plugin.py", line 62, in __init__
              str(QSettings().value("locale/userLocale")).replace(str(NULL), "en_CH")
             NameError: name 'NULL' is not defined

**Comment by 3nids** [comment]
sorry, should be fixed in 1.3.3

**Comment by spch-GL** [comment]
Yes, this is a fix

Pierre Grellet
Chef de projets en informatique technique (DDTE - SPCH - OSMO)

De : Denis Rouzaud ***@***.***>
Envoyé : mercredi, 28 septembre 2022 16:12
À : opengisch/qgis_geomapfish_locator ***@***.***>
Cc : Grellet Pierre ***@***.***>; Author ***@***.***>
Objet : Re: [opengisch/qgis_geomapfish_locator] Sous windows depuis le passage à Geomapfish Locator 1.3.2: Impossible de charger l'extension 'geomapfish_locator' provoque une erreur lors de l'appel à sa méthode classFactory() (Issue #12)

[E-MAIL EXTERNE]


Closed #12<https://github.com/opengisch/qgis_geomapfish_locator/issues/12> as completed via 458267c<https://github.com/opengisch/qgis_geomapfish_locator/commit/458267ce4286ee272eeed32977cc481dfdd69e57>.
