### ISSUE TITLE
Works almost well with MN03

### ISSUE THREAD

**Issue by ponceta** [opengisch/qgis_geomapfish_locator#2]
Hi @3nids,

I've done some tests but I faced some projections errors.

Otherwise, the service seems to work well with gmf fulltextsearch.

![image](https://user-images.githubusercontent.com/8614223/46678752-9c98a980-cbe5-11e8-903f-45e2cce57689.png)

![image](https://user-images.githubusercontent.com/8614223/46678874-e97c8000-cbe5-11e8-92bb-0dd228523114.png)

![image](https://user-images.githubusercontent.com/8614223/46679122-93f4a300-cbe6-11e8-8a46-df6e0c90140e.png)

**Comment by ponceta** [comment]
QGIS 3 crashed, reloaded and it was fine aferwards...

![image](https://user-images.githubusercontent.com/8614223/46679285-f057c280-cbe6-11e8-85c8-f694147f1ac4.png)

**Comment by 3nids** [comment]
do you have the trace of the crash?
do you mean that after it crashes, it works now alway fine?

**Comment by 3nids** [comment]
closing, feel free to reopen if there is an issue.
